### ISSUE TITLE
v1.0.70 BlazeTextViewTableViewCell doneChanging not called

### ISSUE THREAD

**Issue by rajderks** [BobDG/Blaze#14]
When initialising a row with a XIB that has the type BlazeTextViewTableViewCell the row.doneChanging method is not being called after firstResponder has been resigned.

This is the case when either using [self.view endEditing:true]; or the "hide keyboard button" in the lower right corner. 
When using the accessoryView's "done" button the doneChanging is being called correctly.

Tested on iPad

```
//Row
row = [BlazeRow rowWithXibName:XIBWithTextView];
   
row.doneChanging = ^{
   ... not being called
};
```

**Comment by BobDG** [comment]
@rajderks now fixed in build 1.0.71
