### ISSUE TITLE
Swift branch?

### ISSUE THREAD

**Issue by TripwireNL** [BobDG/Blaze#19]
Hey Bob can you make a Swift branch? I've started working on converting everything to Swift 4 and it would be nice to push what I have now in there!

**Comment by BobDG** [comment]
@Tripwire999 Branch created :) Curious to see what you have. Have you been working from the newest version?

**Comment by TripwireNL** [comment]
@BobDG I just pulled the master version Friday and started converting the Objective-c code to Swift 4.0. There are some things I need to think about especially the BlazeRow since it's huge! Maybe better to make seperate objects or something. But let's collaborate :) I'll upload the stuff tonight

**Comment by BobDG** [comment]
@Tripwire999 ok cool! I'm always open to suggestions :) Especially for Swift ;)

**Comment by TripwireNL** [comment]
@BobDG I was sick last week so didn't work / commit to Blaze-Swift branch. So I tried it just now but I get an access denied 403 when pushing to the Swift branch

**Comment by BobDG** [comment]
@Tripwire999 Just made you an collaborator :) Please don't push directly to the master branch though, always use pull requests for that. To the swift branch you can of course push what you want :)

**Comment by TripwireNL** [comment]
@BobDG I'll only push in swift branch :)

**Comment by TripwireNL** [comment]
nvm :P forgot to accept the invitation ^^
